#!/bin/bash
set -euo pipefail

ROOT="/data2/mingyu/composed_image_retrieval"

RUN_NAME="${RUN_NAME:-DistillCIR_ParallelDualLoRA_BS256_Accum2_ViTB32_SEARLEPhi_That_Drop0p3_CIRCO2700}"
MODEL_NAME="ViT-B/32" \
OPENAI_PRETRAINED="1" \
PIC2WORD_CKPT="" \
IMG2TEXT_ARCH="phi" \
IMG2TEXT_PRETRAINED="/data2/mingyu/.cache/torch/hub/checkpoints/SEARLE_ViT-B32.pt" \
MIDDLE_DIM="2048" \
RETRIEVAL_PROMPT_CONNECTOR="that" \
TRAIN_CUDA_DEVICES="4,5" \
DIST_URL="tcp://127.0.0.1:6197" \
RUN_NAME="${RUN_NAME}" \
TRAIN_BATCH_SIZE="256" \
TRAIN_ACCUM_STEPS="2" \
LR="2e-5" \
GEO_LR="2e-5" \
INSTRUCTION_DROPOUT_PROB="0.3" \
TRAIN_EPOCH_STEPS="2700" \
SAVE_STEP_START="1700" \
SAVE_STEP_END="2700" \
SAVE_STEP_INTERVAL="200" \
RUN_POSTHOC_MERGED_EVAL="0" \
RUN_POSTHOC_SECOND_MERGED_EVAL="0" \
RUN_POSTHOC_CIRR_EVAL="0" \
MULTIDATASET_EVAL_EVERY="0" \
CIRR_VAL_EVAL_EVERY="0" \
bash "${ROOT}/train_with_dropout.sh"
