#!/bin/bash
set -euo pipefail

ROOT="/data2/mingyu/composed_image_retrieval"

MODEL_NAME="ViT-L/14" \
OPENAI_PRETRAINED="1" \
PIC2WORD_CKPT="" \
IMG2TEXT_ARCH="phi" \
IMG2TEXT_PRETRAINED="/data2/mingyu/.cache/torch/hub/checkpoints/SEARLE_ViT-L14.pt" \
MIDDLE_DIM="3072" \
RETRIEVAL_PROMPT_CONNECTOR="that" \
TRAIN_CUDA_DEVICES="6,7" \
DIST_URL="tcp://127.0.0.1:6322" \
RUN_NAME="DistillCIR_ParallelDualLoRA_BS56_Accum8_ViTL14_SEARLEPhi_That_Drop0p5_GeoOnly_CIRCO_GeneCIS" \
TRAIN_BATCH_SIZE="56" \
TRAIN_ACCUM_STEPS="8" \
LR="2e-5" \
GEO_LR="2e-5" \
INSTRUCTION_DROPOUT_PROB="0.5" \
TRAIN_EPOCH_STEPS="1400" \
SAVE_STEP_START="1400" \
SAVE_STEP_END="1400" \
SAVE_STEP_INTERVAL="200" \
SHARED_B_LORA="0" \
SHARED_B_RETRIEVAL_ONLY_UPDATE="0" \
JOINT_SINGLE_BRANCH="0" \
GEO_ONLY_BRANCH="1" \
ENABLE_GEO_CONFLICT_PROJECTION="0" \
GEO_REVERSE_WEIGHT="0.0" \
GEO_ZERO_LOSS_WEIGHT="1.0" \
RUN_POSTHOC_MERGED_EVAL="0" \
RUN_POSTHOC_SECOND_MERGED_EVAL="0" \
RUN_POSTHOC_CIRR_EVAL="0" \
MULTIDATASET_EVAL_EVERY="0" \
CIRR_VAL_EVAL_EVERY="0" \
bash "${ROOT}/train_with_dropout.sh"
